package Modelo.entities;
// Generated 25-abr-2020 18:15:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * InvoicesDetails generated by hbm2java
 */
public class InvoicesDetails  implements java.io.Serializable {


     private int id;
     private Invoices invoices;
     private Products products;
     private Users usersByCreatedBy;
     private Users usersByModifiedBy;
     private double price;
     private int quantity;
     private double subTotal;
     private double iva;
     private double total;
     private Date createdDate;
     private Date modifiedDate;

    public InvoicesDetails() {
    }

	
    public InvoicesDetails(int id, Invoices invoices, Products products, Users usersByCreatedBy, Users usersByModifiedBy, double price, int quantity, double subTotal, double iva, double total, Date modifiedDate) {
        this.id = id;
        this.invoices = invoices;
        this.products = products;
        this.usersByCreatedBy = usersByCreatedBy;
        this.usersByModifiedBy = usersByModifiedBy;
        this.price = price;
        this.quantity = quantity;
        this.subTotal = subTotal;
        this.iva = iva;
        this.total = total;
        this.modifiedDate = modifiedDate;
    }
    public InvoicesDetails(int id, Invoices invoices, Products products, Users usersByCreatedBy, Users usersByModifiedBy, double price, int quantity, double subTotal, double iva, double total, Date createdDate, Date modifiedDate) {
       this.id = id;
       this.invoices = invoices;
       this.products = products;
       this.usersByCreatedBy = usersByCreatedBy;
       this.usersByModifiedBy = usersByModifiedBy;
       this.price = price;
       this.quantity = quantity;
       this.subTotal = subTotal;
       this.iva = iva;
       this.total = total;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Invoices getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Invoices invoices) {
        this.invoices = invoices;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Users getUsersByCreatedBy() {
        return this.usersByCreatedBy;
    }
    
    public void setUsersByCreatedBy(Users usersByCreatedBy) {
        this.usersByCreatedBy = usersByCreatedBy;
    }
    public Users getUsersByModifiedBy() {
        return this.usersByModifiedBy;
    }
    
    public void setUsersByModifiedBy(Users usersByModifiedBy) {
        this.usersByModifiedBy = usersByModifiedBy;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(double subTotal) {
        this.subTotal = subTotal;
    }
    public double getIva() {
        return this.iva;
    }
    
    public void setIva(double iva) {
        this.iva = iva;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


