package Modelo.entities;
// Generated 25-abr-2020 18:15:55 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private int id;
     private ProductsCategories productsCategories;
     private Users usersByCreatedBy;
     private Users usersByModifiedBy;
     private Serializable name;
     private Serializable shortName;
     private Serializable description;
     private double price;
     private Date createdDate;
     private Date modifiedDate;
     private Set invoicesDetailses = new HashSet(0);

    public Products() {
    }

	
    public Products(int id, ProductsCategories productsCategories, Users usersByCreatedBy, Users usersByModifiedBy, Serializable name, Serializable shortName, Serializable description, double price, Date modifiedDate) {
        this.id = id;
        this.productsCategories = productsCategories;
        this.usersByCreatedBy = usersByCreatedBy;
        this.usersByModifiedBy = usersByModifiedBy;
        this.name = name;
        this.shortName = shortName;
        this.description = description;
        this.price = price;
        this.modifiedDate = modifiedDate;
    }
    public Products(int id, ProductsCategories productsCategories, Users usersByCreatedBy, Users usersByModifiedBy, Serializable name, Serializable shortName, Serializable description, double price, Date createdDate, Date modifiedDate, Set invoicesDetailses) {
       this.id = id;
       this.productsCategories = productsCategories;
       this.usersByCreatedBy = usersByCreatedBy;
       this.usersByModifiedBy = usersByModifiedBy;
       this.name = name;
       this.shortName = shortName;
       this.description = description;
       this.price = price;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.invoicesDetailses = invoicesDetailses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ProductsCategories getProductsCategories() {
        return this.productsCategories;
    }
    
    public void setProductsCategories(ProductsCategories productsCategories) {
        this.productsCategories = productsCategories;
    }
    public Users getUsersByCreatedBy() {
        return this.usersByCreatedBy;
    }
    
    public void setUsersByCreatedBy(Users usersByCreatedBy) {
        this.usersByCreatedBy = usersByCreatedBy;
    }
    public Users getUsersByModifiedBy() {
        return this.usersByModifiedBy;
    }
    
    public void setUsersByModifiedBy(Users usersByModifiedBy) {
        this.usersByModifiedBy = usersByModifiedBy;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public Serializable getShortName() {
        return this.shortName;
    }
    
    public void setShortName(Serializable shortName) {
        this.shortName = shortName;
    }
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set getInvoicesDetailses() {
        return this.invoicesDetailses;
    }
    
    public void setInvoicesDetailses(Set invoicesDetailses) {
        this.invoicesDetailses = invoicesDetailses;
    }




}


