package Modelo.entities;
// Generated 25-abr-2020 18:15:55 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductsCategories generated by hbm2java
 */
public class ProductsCategories  implements java.io.Serializable {


     private int id;
     private Users usersByModifiedBy;
     private Users usersByCreatedBy;
     private Serializable code;
     private Serializable name;
     private Date createdDate;
     private Date modifiedDate;
     private Set productses = new HashSet(0);

    public ProductsCategories() {
    }

	
    public ProductsCategories(int id, Users usersByModifiedBy, Users usersByCreatedBy, Serializable code, Serializable name, Date modifiedDate) {
        this.id = id;
        this.usersByModifiedBy = usersByModifiedBy;
        this.usersByCreatedBy = usersByCreatedBy;
        this.code = code;
        this.name = name;
        this.modifiedDate = modifiedDate;
    }
    public ProductsCategories(int id, Users usersByModifiedBy, Users usersByCreatedBy, Serializable code, Serializable name, Date createdDate, Date modifiedDate, Set productses) {
       this.id = id;
       this.usersByModifiedBy = usersByModifiedBy;
       this.usersByCreatedBy = usersByCreatedBy;
       this.code = code;
       this.name = name;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.productses = productses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Users getUsersByModifiedBy() {
        return this.usersByModifiedBy;
    }
    
    public void setUsersByModifiedBy(Users usersByModifiedBy) {
        this.usersByModifiedBy = usersByModifiedBy;
    }
    public Users getUsersByCreatedBy() {
        return this.usersByCreatedBy;
    }
    
    public void setUsersByCreatedBy(Users usersByCreatedBy) {
        this.usersByCreatedBy = usersByCreatedBy;
    }
    public Serializable getCode() {
        return this.code;
    }
    
    public void setCode(Serializable code) {
        this.code = code;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


