package Modelo.entities;
// Generated 25-abr-2020 18:15:55 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sexs generated by hbm2java
 */
public class Sexs  implements java.io.Serializable {


     private int id;
     private Users usersByCreatedBy;
     private Users usersByModifiedBy;
     private Serializable code;
     private Serializable name;
     private Date createdDate;
     private Date modifiedDate;
     private Set clientses = new HashSet(0);
     private Set memberses = new HashSet(0);

    public Sexs() {
    }

	
    public Sexs(int id, Users usersByCreatedBy, Users usersByModifiedBy, Serializable code, Serializable name, Date createdDate, Date modifiedDate) {
        this.id = id;
        this.usersByCreatedBy = usersByCreatedBy;
        this.usersByModifiedBy = usersByModifiedBy;
        this.code = code;
        this.name = name;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
    }
    public Sexs(int id, Users usersByCreatedBy, Users usersByModifiedBy, Serializable code, Serializable name, Date createdDate, Date modifiedDate, Set clientses, Set memberses) {
       this.id = id;
       this.usersByCreatedBy = usersByCreatedBy;
       this.usersByModifiedBy = usersByModifiedBy;
       this.code = code;
       this.name = name;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.clientses = clientses;
       this.memberses = memberses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Users getUsersByCreatedBy() {
        return this.usersByCreatedBy;
    }
    
    public void setUsersByCreatedBy(Users usersByCreatedBy) {
        this.usersByCreatedBy = usersByCreatedBy;
    }
    public Users getUsersByModifiedBy() {
        return this.usersByModifiedBy;
    }
    
    public void setUsersByModifiedBy(Users usersByModifiedBy) {
        this.usersByModifiedBy = usersByModifiedBy;
    }
    public Serializable getCode() {
        return this.code;
    }
    
    public void setCode(Serializable code) {
        this.code = code;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set getClientses() {
        return this.clientses;
    }
    
    public void setClientses(Set clientses) {
        this.clientses = clientses;
    }
    public Set getMemberses() {
        return this.memberses;
    }
    
    public void setMemberses(Set memberses) {
        this.memberses = memberses;
    }




}


