package ui_javastore.model.entities;
// Generated 23-abr-2020 12:38:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoices generated by hbm2java
 */
public class Invoices  implements java.io.Serializable {


     private int id;
     private Clients clients;
     private Users usersByCreatedBy;
     private Users usersByModifiedBy;
     private Date createdDate;
     private Date modifiedDate;
     private Set invoicesDetailses = new HashSet(0);

    public Invoices() {
    }

	
    public Invoices(int id, Clients clients, Users usersByCreatedBy, Users usersByModifiedBy, Date modifiedDate) {
        this.id = id;
        this.clients = clients;
        this.usersByCreatedBy = usersByCreatedBy;
        this.usersByModifiedBy = usersByModifiedBy;
        this.modifiedDate = modifiedDate;
    }
    public Invoices(int id, Clients clients, Users usersByCreatedBy, Users usersByModifiedBy, Date createdDate, Date modifiedDate, Set invoicesDetailses) {
       this.id = id;
       this.clients = clients;
       this.usersByCreatedBy = usersByCreatedBy;
       this.usersByModifiedBy = usersByModifiedBy;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
       this.invoicesDetailses = invoicesDetailses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public Users getUsersByCreatedBy() {
        return this.usersByCreatedBy;
    }
    
    public void setUsersByCreatedBy(Users usersByCreatedBy) {
        this.usersByCreatedBy = usersByCreatedBy;
    }
    public Users getUsersByModifiedBy() {
        return this.usersByModifiedBy;
    }
    
    public void setUsersByModifiedBy(Users usersByModifiedBy) {
        this.usersByModifiedBy = usersByModifiedBy;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set getInvoicesDetailses() {
        return this.invoicesDetailses;
    }
    
    public void setInvoicesDetailses(Set invoicesDetailses) {
        this.invoicesDetailses = invoicesDetailses;
    }




}


