/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kevin;

import java.awt.Color;

/**
 *
 * @author Ara-PC
 */
public class Encriptacion extends javax.swing.JFrame {

    /**
     * Creates new form Encriptacion
     */
    public Encriptacion() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfrase = new javax.swing.JTextField();
        txtencriptada = new javax.swing.JTextField();
        txtdesencriptada = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(108, 99, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Encriptacion ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, 80));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kevin/icons8_protect_70px.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, 80));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kevin/icons8_protect_70px.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 80));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(63, 61, 86));
        jLabel1.setText("Frase");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(63, 61, 86));
        jLabel2.setText("Encriptada");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(63, 61, 86));
        jLabel3.setText("Desencriptada");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, 40));

        txtfrase.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtfrase.setForeground(new java.awt.Color(63, 61, 86));
        txtfrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfraseActionPerformed(evt);
            }
        });
        jPanel1.add(txtfrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 310, 40));

        txtencriptada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtencriptada.setForeground(new java.awt.Color(63, 61, 86));
        jPanel1.add(txtencriptada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 310, 40));

        txtdesencriptada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdesencriptada.setForeground(new java.awt.Color(63, 61, 86));
        jPanel1.add(txtdesencriptada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 310, 40));

        jPanel3.setBackground(new java.awt.Color(108, 99, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Encriptar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 280, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        setBounds(0, 0, 707, 389);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfraseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfraseActionPerformed

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(63, 61, 86));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(108, 99, 255));
    }//GEN-LAST:event_jPanel3MouseExited
    static int[][] encrypt(int plainText[][], int cipherText[][], String message, int rowCount, int columnCount, String key) {
        int i, j;
        int k = 0;
        for (i = 0; i < rowCount; i++) {
            for (j = 0; j < columnCount; j++) {
                if (k < message.length()) {
                    plainText[i][j] = (int) message.charAt(k);
                    k++;
                } else {
                    break;
                }
            }
        }
        for (i = 0; i < columnCount; i++) {
            int currentCol = ((int) key.charAt(i) - 48) - 1;
            for (j = 0; j < rowCount; j++) {
                cipherText[j][i] = plainText[j][currentCol];
            }
        }
        //System.out.print("Cipher Array(read column by column): \n");
        for (i = 0; i < rowCount; i++) {
            for (j = 0; j < columnCount; j++) {
                //System.out.print((char) cipherText[i][j] + "\t");
            }
            System.out.println();
        }
        return cipherText;
    }

    static int[][] decrypt(int plainText[][], int cipherText[][], String message, int rowCount, int columnCount, String key) {
        int i, j;
        int k = 0;
        for (i = 0; i < columnCount; i++) {
            int currentCol = ((int) key.charAt(i) - 48) - 1;
            for (j = 0; j < rowCount; j++) {
                plainText[j][currentCol] = cipherText[j][i];
            }
        }
        //  System.out.print("Plain Array(read row by row): \n");
        for (i = 0; i < rowCount; i++) {
            for (j = 0; j < columnCount; j++) {
                //System.out.print((char) plainText[i][j] + "\t");
            }
            System.out.println();
        }
        return plainText;
    }
    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        String message = txtfrase.getText().replaceAll("\\s", "");
        String key = "12345";
        int columnCount = key.length();
        int rowCount = (message.length() + columnCount) / columnCount;
        int plainText[][] = new int[rowCount][columnCount];
        int cipherText[][] = new int[rowCount][columnCount];

        cipherText = encrypt(plainText, cipherText, message, rowCount, columnCount, key);
        String ct = "";
        for (int i = 0; i < columnCount; i++) {
            for (int j = 0; j < rowCount; j++) {
                if (cipherText[j][i] == 0) {
                    ct = ct;
                } else {
                    ct = ct + (char) cipherText[j][i];
                }
            }
        }

        plainText = decrypt(plainText, cipherText, ct, rowCount, columnCount, key);
        String pt = "";
        for (int i = 0; i < rowCount; i++) {
            for (int j = 0; j < columnCount; j++) {
                if (plainText[i][j] == 0) {
                    pt = pt + "";
                } else {
                    pt = pt + (char) plainText[i][j];
                }
            }
        }

        txtencriptada.setText(ct);
        txtdesencriptada.setText(pt);
        /*String info[][] = new String[p.size()][3];
            modelo.addRow(info);*/
       


    }//GEN-LAST:event_jPanel3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encriptacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encriptacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encriptacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encriptacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encriptacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtdesencriptada;
    private javax.swing.JTextField txtencriptada;
    private javax.swing.JTextField txtfrase;
    // End of variables declaration//GEN-END:variables
}
