/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.awt.Color;
import java.awt.Font;
import javax.swing.DefaultComboBoxModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ara-PC
 */
public class Ventana extends javax.swing.JFrame {

    private DefaultComboBoxModel<Persona> modelo = new DefaultComboBoxModel<Persona>();
    private DefaultTableModel modeloTabla = new DefaultTableModel();

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        llenarModelo();
        agregarModeloTabla();
        initComponents();
       setLocationRelativeTo(null);
      
    }

    private void agregarModeloTabla() {

        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Telefono");
        modeloTabla.addColumn("Email");
        modeloTabla.addColumn("Direccion");
    }

    private void llenarModelo() {
        modelo.addElement(new Persona("Kevin", "Esquivel", "kevinesquivel@hotmaial.com", "managua", String.valueOf(88862060)));
        modelo.addElement(new Persona("Daniela", "Torrez", "Daniela@hotmaial.com", "managua", String.valueOf(88862060)));
        modelo.addElement(new Persona("Jose", "Calderon", "jose@hotmaial.com", "managua", String.valueOf(88862060)));
        modelo.addElement(new Persona("Hanny", "Zeledon", "Hanny@hotmaial.com", "managua", String.valueOf(88862060)));
        modelo.addElement(new Persona("Bryan", "Zeledon", "Bryan@hotmaial.com", "managua", String.valueOf(88862060)));
        modelo.addElement(new Persona("Ara", "Rojas", "Ara@hotmaial.com", "managua", String.valueOf(88862060)));
        modelo.addElement(new Persona("Samuel", "Esquivel", "Samuel@hotmaial.com", "managua", String.valueOf(88862060)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        comboPersona = new javax.swing.JComboBox<>();
        scrollPane = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(20, 40, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, 585, 10));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Persona");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, -1, -1));

        comboPersona.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboPersona.setModel(modelo);
        jPanel2.add(comboPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, 206, 34));

        tabla.setAutoCreateRowSorter(true);
        tabla.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabla.setModel(modeloTabla);
        tabla.setFocusable(false);
        tabla.setGridColor(new java.awt.Color(102, 102, 102));
        tabla.setInheritsPopupMenu(true);
        tabla.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabla.setPreferredSize(new java.awt.Dimension(100, 64));
        tabla.setRowHeight(25);
        tabla.setSelectionBackground(new java.awt.Color(247, 130, 89));
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla.setShowVerticalLines(false);
        tabla.getTableHeader().setResizingAllowed(false);
        tabla.getTableHeader().setReorderingAllowed(false);
        //Oyente de seleccion que permite seleccionar una fila de la tabla
        ListSelectionListener oyenteSelection = new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e){

                if(e.getValueIsAdjusting()){
                    //System.out.println("Fila seleccionada");
                    int fila_Seleccionada_ = tabla.getSelectedRow();//Retorna el numero de la fila seleccionada
                    String nombre = (String) modeloTabla.getValueAt(fila_Seleccionada_, 0);
                    String apellido = (String) modeloTabla.getValueAt(fila_Seleccionada_, 1);
                    String telefono = (String) modeloTabla.getValueAt(fila_Seleccionada_, 2);
                    String email = (String) modeloTabla.getValueAt(fila_Seleccionada_, 3);
                    String direccion = (String) modeloTabla.getValueAt(fila_Seleccionada_, 4);

                    //Pasamos los atos

                    txtnombre.setText(nombre);
                    txtapellido.setText(apellido);
                    txttelefono.setText(telefono);
                    txtemail.setText(email);
                    txtdireccion.setText(direccion);

                }
            }

        };

        tabla.getSelectionModel().addListSelectionListener(oyenteSelection);
        scrollPane.setViewportView(tabla);

        jPanel2.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, 585, 132));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos de la Persona");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 321, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 305, 585, 10));

        txtnombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 408, 192, 32));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 381, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 381, -1, -1));

        txtapellido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel2.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 408, 188, 32));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 495, -1, -1));

        txttelefono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel2.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 192, 34));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 500, -1, -1));

        txtemail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 522, 196, 32));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Direccion");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 596, -1, -1));

        txtdireccion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        jPanel2.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 560, 34));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AGENDA PERSONAL ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 13, -1, -1));

        jButton2.setBackground(new java.awt.Color(247, 130, 89));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Insertar Persona");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 83, 191, 45));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           Persona p = (Persona) comboPersona.getSelectedItem();

        String nombre = p.getNombre();
        String apellido = p.getApellido();
        String telefono = p.getTelefono();
        String direccion = p.getDireccion();
        String email = p.getEmial();
        
        String [] perosna = {nombre,apellido,telefono,email,direccion};
        modeloTabla.addRow(perosna);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Persona> comboPersona;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
