/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_interfaz01;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Ara-PC
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        panel_Prncipal.setOpaque(true);
        // setSize(900, 550);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Prncipal = new javax.swing.JPanel();
        panel_home = new javax.swing.JPanel();
        lbl_home = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_header = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panel_students = new javax.swing.JPanel();
        lbl_students = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel_timetable = new javax.swing.JPanel();
        lbl_students1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_settings = new javax.swing.JPanel();
        lbl_settings = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panel_classes = new javax.swing.JPanel();
        lbl_classes = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel_update = new javax.swing.JPanel();
        lbl_update = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_Prncipal.setBackground(new java.awt.Color(255, 255, 255));
        panel_Prncipal.setPreferredSize(new java.awt.Dimension(900, 630));
        panel_Prncipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_home.setBackground(new java.awt.Color(255, 255, 255));
        panel_home.setPreferredSize(new java.awt.Dimension(90, 90));
        panel_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_homeMousePressed(evt);
            }
        });

        lbl_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_interfaz01/Imagenes/icons8_home_50px_1.png"))); // NOI18N
        lbl_home.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 118, 232));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_homeLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_home, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_homeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbl_home, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        panel_Prncipal.add(panel_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 140, 140));

        panel_header.setBackground(new java.awt.Color(45, 118, 232));
        panel_header.setPreferredSize(new java.awt.Dimension(950, 100));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("KeepToo");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("School Management");

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_interfaz01/Imagenes/icons8_cancel_50px.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(45, 118, 232));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_interfaz01/Imagenes/icons8_search_30px_1.png"))); // NOI18N

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_interfaz01/Imagenes/icons8_school_house_80px_1.png"))); // NOI18N

        javax.swing.GroupLayout panel_headerLayout = new javax.swing.GroupLayout(panel_header);
        panel_header.setLayout(panel_headerLayout);
        panel_headerLayout.setHorizontalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_headerLayout.createSequentialGroup()
                        .addGroup(panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(panel_headerLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_headerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 521, Short.MAX_VALUE)
                        .addComponent(exit)
                        .addGap(52, 52, 52))
                    .addGroup(panel_headerLayout.createSequentialGroup()
                        .addGroup(panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_headerLayout.setVerticalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_headerLayout.createSequentialGroup()
                .addGroup(panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_headerLayout.createSequentialGroup()
                        .addComponent(exit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_headerLayout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_Prncipal.add(panel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 210));

        panel_students.setBackground(new java.awt.Color(255, 255, 255));
        panel_students.setPreferredSize(new java.awt.Dimension(90, 90));
        panel_students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_studentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_studentsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_studentsMousePressed(evt);
            }
        });

        lbl_students.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_students.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_interfaz01/Imagenes/icons8_user_account_50px.png"))); // NOI18N
        lbl_students.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_students.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 118, 232));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Students");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_studentsLayout = new javax.swing.GroupLayout(panel_students);
        panel_students.setLayout(panel_studentsLayout);
        panel_studentsLayout.setHorizontalGroup(
            panel_studentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_studentsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panel_studentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_students, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        panel_studentsLayout.setVerticalGroup(
            panel_studentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_studentsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbl_students)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        panel_Prncipal.add(panel_students, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 140, 140));

        panel_timetable.setBackground(new java.awt.Color(255, 255, 255));
        panel_timetable.setPreferredSize(new java.awt.Dimension(90, 90));
        panel_timetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_timetableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_timetableMouseExited(evt);
            }
        });

        lbl_students1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_students1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_interfaz01/Imagenes/icons8_classroom_50px.png"))); // NOI18N
        lbl_students1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_students1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 118, 232));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Timetable");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_timetableLayout = new javax.swing.GroupLayout(panel_timetable);
        panel_timetable.setLayout(panel_timetableLayout);
        panel_timetableLayout.setHorizontalGroup(
            panel_timetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_timetableLayout.createSequentialGroup()
                .addGroup(panel_timetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_timetableLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_students1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_timetableLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(56, 56, 56))
        );
        panel_timetableLayout.setVerticalGroup(
            panel_timetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_timetableLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbl_students1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        panel_Prncipal.add(panel_timetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 140, 140));

        panel_settings.setBackground(new java.awt.Color(255, 255, 255));
        panel_settings.setPreferredSize(new java.awt.Dimension(90, 90));
        panel_settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_settingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_settingsMouseExited(evt);
            }
        });

        lbl_settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_interfaz01/Imagenes/icons8_settings_50px.png"))); // NOI18N
        lbl_settings.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_settings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 118, 232));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Settings");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_settingsLayout = new javax.swing.GroupLayout(panel_settings);
        panel_settings.setLayout(panel_settingsLayout);
        panel_settingsLayout.setHorizontalGroup(
            panel_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_settingsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panel_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_settings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        panel_settingsLayout.setVerticalGroup(
            panel_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_settingsLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lbl_settings)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        panel_Prncipal.add(panel_settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 140, 140));

        panel_classes.setBackground(new java.awt.Color(255, 255, 255));
        panel_classes.setPreferredSize(new java.awt.Dimension(90, 90));
        panel_classes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_classesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_classesMouseExited(evt);
            }
        });

        lbl_classes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_classes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_interfaz01/Imagenes/icons8_list_50px.png"))); // NOI18N
        lbl_classes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_classes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 118, 232));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Classes");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_classesLayout = new javax.swing.GroupLayout(panel_classes);
        panel_classes.setLayout(panel_classesLayout);
        panel_classesLayout.setHorizontalGroup(
            panel_classesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_classesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panel_classesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_classes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        panel_classesLayout.setVerticalGroup(
            panel_classesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_classesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbl_classes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        panel_Prncipal.add(panel_classes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 140, 140));

        panel_update.setBackground(new java.awt.Color(255, 255, 255));
        panel_update.setPreferredSize(new java.awt.Dimension(90, 90));
        panel_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_updateMouseExited(evt);
            }
        });

        lbl_update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_interfaz01/Imagenes/icons8_download_50px.png"))); // NOI18N
        lbl_update.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_update.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 118, 232));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Update");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_updateLayout = new javax.swing.GroupLayout(panel_update);
        panel_update.setLayout(panel_updateLayout);
        panel_updateLayout.setHorizontalGroup(
            panel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_updateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_updateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_update, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        panel_updateLayout.setVerticalGroup(
            panel_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_updateLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_update)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panel_Prncipal.add(panel_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 140, 140));

        getContentPane().add(panel_Prncipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void panel_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_homeMouseEntered
        // TODO add your handling code here:
        setColor(panel_home);
    }//GEN-LAST:event_panel_homeMouseEntered

    private void panel_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_homeMouseExited
        // TODO add your handling code here:
        resetColor(panel_home);
    }//GEN-LAST:event_panel_homeMouseExited

    private void panel_studentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_studentsMouseEntered
         setColor(panel_students);
    }//GEN-LAST:event_panel_studentsMouseEntered

    private void panel_studentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_studentsMouseExited
         resetColor(panel_students);
    }//GEN-LAST:event_panel_studentsMouseExited

    private void panel_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_homeMouseClicked
       
        
        
    }//GEN-LAST:event_panel_homeMouseClicked

    private void panel_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_homeMousePressed
        // TODO add your handling code here:
        new Submenu().show();
        dispose();
        
    }//GEN-LAST:event_panel_homeMousePressed

    private void panel_timetableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_timetableMouseExited
        // TODO add your handling code here:
        resetColor(panel_timetable);
    }//GEN-LAST:event_panel_timetableMouseExited

    private void panel_timetableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_timetableMouseEntered
        // TODO add your handling code here:
         setColor(panel_timetable);
    }//GEN-LAST:event_panel_timetableMouseEntered

    private void panel_settingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_settingsMouseEntered
        // TODO add your handling code here:
         setColor(panel_settings);
    }//GEN-LAST:event_panel_settingsMouseEntered

    private void panel_settingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_settingsMouseExited
        resetColor(panel_settings);
    }//GEN-LAST:event_panel_settingsMouseExited

    private void panel_classesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_classesMouseEntered
        // TODO add your handling code here:
        setColor(panel_classes);
    }//GEN-LAST:event_panel_classesMouseEntered

    private void panel_classesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_classesMouseExited
        // TODO add your handling code here:
        resetColor(panel_classes);
    }//GEN-LAST:event_panel_classesMouseExited

    private void panel_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_updateMouseEntered
        // TODO add your handling code here:
        setColor(panel_update);
    }//GEN-LAST:event_panel_updateMouseEntered

    private void panel_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_updateMouseExited
        // TODO add your handling code here:
        resetColor(panel_update);
    }//GEN-LAST:event_panel_updateMouseExited

    private void panel_studentsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_studentsMousePressed
        // TODO add your handling code here:
        new Students().show();
        dispose();
    }//GEN-LAST:event_panel_studentsMousePressed

    public void setColor(JPanel panel) {
        panel.setBackground(new Color(115, 163, 239));

    }

    public void resetColor(JPanel panel) {
       panel.setBackground(new Color(255, 255, 255));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_classes;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_settings;
    private javax.swing.JLabel lbl_students;
    private javax.swing.JLabel lbl_students1;
    private javax.swing.JLabel lbl_update;
    private javax.swing.JPanel panel_Prncipal;
    private javax.swing.JPanel panel_classes;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_settings;
    private javax.swing.JPanel panel_students;
    private javax.swing.JPanel panel_timetable;
    private javax.swing.JPanel panel_update;
    // End of variables declaration//GEN-END:variables
}
