/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_md5;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Font;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ara-PC
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int x;
    int y;
    
    

    public Login() {
        this.setUndecorated(true);
        initComponents();
        
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        AWTUtilities.setWindowShape(this, forma);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_principal = new javax.swing.JPanel();
        txtpass = new javax.swing.JPasswordField();
        lbl_informcion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_of = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_Login = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_principal.setBackground(new java.awt.Color(255, 255, 255));
        panel_principal.setFocusable(false);
        panel_principal.setMinimumSize(new java.awt.Dimension(600, 650));
        panel_principal.setOpaque(false);
        panel_principal.setPreferredSize(new java.awt.Dimension(600, 650));
        panel_principal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_principalMouseDragged(evt);
            }
        });
        panel_principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_principalMousePressed(evt);
            }
        });
        panel_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtpass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtpass.setForeground(new java.awt.Color(63, 61, 86));
        txtpass.setText("Click Password ...");
        txtpass.setBorder(null);
        txtpass.setOpaque(false);
        txtpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpassMousePressed(evt);
            }
        });
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
        });
        panel_principal.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 270, 30));

        lbl_informcion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lbl_informcion.setForeground(new java.awt.Color(245, 0, 87));
        lbl_informcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_principal.add(lbl_informcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 350, 20));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(245, 0, 87));
        jLabel8.setText("Log In");
        panel_principal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, -1, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(63, 61, 86));
        jLabel7.setText("Already  have an account?");
        panel_principal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 190, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(63, 61, 86));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create Account");
        panel_principal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 220, 50));

        lbl_of.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_of.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_power_off_button_45px.png"))); // NOI18N
        lbl_of.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ofMouseClicked(evt);
            }
        });
        panel_principal.add(lbl_of, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 40, 40));

        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/security.png"))); // NOI18N
        panel_principal.add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 270, 230));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Security");
        panel_principal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 180, 40));

        jLabel3.setBackground(new java.awt.Color(63, 61, 86));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(63, 61, 86));
        jLabel3.setText("Username");
        panel_principal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jLabel4.setBackground(new java.awt.Color(63, 61, 86));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(63, 61, 86));
        jLabel4.setText("Password");
        panel_principal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        txtuser.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtuser.setForeground(new java.awt.Color(63, 61, 86));
        txtuser.setText("Click Username ...");
        txtuser.setToolTipText("");
        txtuser.setBorder(null);
        txtuser.setOpaque(false);
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtuserMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtuserMousePressed(evt);
            }
        });
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuserKeyPressed(evt);
            }
        });
        panel_principal.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 270, 30));

        jSeparator1.setBackground(new java.awt.Color(63, 61, 86));
        jSeparator1.setForeground(new java.awt.Color(63, 61, 86));
        jSeparator1.setToolTipText("");
        panel_principal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 310, 10));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_25px_1.png"))); // NOI18N
        panel_principal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 30, 30));

        jSeparator2.setBackground(new java.awt.Color(63, 61, 86));
        jSeparator2.setForeground(new java.awt.Color(63, 61, 86));
        panel_principal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 310, 10));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_password_25px_1.png"))); // NOI18N
        panel_principal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, 30));

        jPanel1.setBackground(new java.awt.Color(63, 61, 86));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Join Us");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -7, 100, 50));

        panel_principal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 250, 40));

        lbl_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lll.png"))); // NOI18N
        panel_principal.add(lbl_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 420, 630));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo s_1.png"))); // NOI18N
        panel_principal.add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 650));

        getContentPane().add(panel_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel_principalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_principalMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panel_principalMousePressed

    private void panel_principalMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_principalMouseDragged
        // TODO add your handling code here:
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        this.setLocation(x1 - x, y1 - y);
    }//GEN-LAST:event_panel_principalMouseDragged

    private void txtuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMousePressed
        // TODO add your handling code here:

        String user = "Click Username ...";

        if (user.equals(txtuser.getText())) {
            txtuser.setText("");
            jSeparator2.setBackground(new Color(245, 0, 87));
            jSeparator2.setForeground(new Color(245, 0, 87));
            jSeparator1.setBackground(new Color(63, 61, 86));
            jSeparator1.setForeground(new Color(63, 61, 86));
        } else {
            jSeparator2.setBackground(new Color(245, 0, 87));
            jSeparator2.setForeground(new Color(245, 0, 87));
            jSeparator1.setBackground(new Color(63, 61, 86));
            jSeparator1.setForeground(new Color(63, 61, 86));
            lbl_informcion.setText("");
        }

    }//GEN-LAST:event_txtuserMousePressed

    private void lbl_ofMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ofMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbl_ofMouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        setColor(jPanel1);

    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
        resetColor(jPanel1);
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        String usuario = "admin";
        String pass = "admin";
        String pas = "";
        char con[] = txtpass.getPassword();

        for (int i = 0; i < con.length; i++) {
            pas += con[i];

        }
        if (usuario.equals(txtuser.getText()) && pas.equals(pass)) {
           encrip md = new encrip();
           md.setVisible(true);
            setVisible(false);
        } else if (txtuser.getText().isEmpty() || pas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo obligatorio");
        } else {
            lbl_informcion.setText("Usuario y/o Contraeña Incorrecta");
        }
    }//GEN-LAST:event_jPanel1MousePressed

    private void txtuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtuserMouseClicked

    private void txtuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyPressed
        // TODO add your handling code here:
        String user = "Click Username ...";

        if (user.equals(txtuser.getText())) {
            txtuser.setText("");
            jSeparator2.setBackground(new Color(245, 0, 87));
            jSeparator2.setForeground(new Color(245, 0, 87));
            jSeparator1.setBackground(new Color(63, 61, 86));
            jSeparator1.setForeground(new Color(63, 61, 86));
        } else {
            jSeparator2.setBackground(new Color(245, 0, 87));
            jSeparator2.setForeground(new Color(245, 0, 87));
            jSeparator1.setBackground(new Color(63, 61, 86));
            jSeparator1.setForeground(new Color(63, 61, 86));
            lbl_informcion.setText("");
        }

    }//GEN-LAST:event_txtuserKeyPressed

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed
        // TODO add your handling code here:
        String pas = "";
        String pass = "Click Password ...";
        char con[] = txtpass.getPassword();

        for (int i = 0; i < con.length; i++) {
            pas += con[i];

        }
        if (pass.equals(pas)) {
            txtpass.setText("");
            jSeparator1.setBackground(new Color(245, 0, 87));
            jSeparator1.setForeground(new Color(245, 0, 87));
            jSeparator2.setBackground(new Color(63, 61, 86));
            jSeparator2.setForeground(new Color(63, 61, 86));
        } else {
            jSeparator1.setBackground(new Color(245, 0, 87));
            jSeparator1.setForeground(new Color(245, 0, 87));
            jSeparator2.setBackground(new Color(63, 61, 86));
            jSeparator2.setForeground(new Color(63, 61, 86));
             lbl_informcion.setText("");
        }
    }//GEN-LAST:event_txtpassKeyPressed

    private void txtpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassMousePressed
        // TODO add your handling code here:
        String pas = "";
        String pass = "Click Password ...";
        char con[] = txtpass.getPassword();

        for (int i = 0; i < con.length; i++) {
            pas += con[i];

        }
        if (pass.equals(pas)) {
            txtpass.setText("");
            jSeparator1.setBackground(new Color(245, 0, 87));
            jSeparator1.setForeground(new Color(245, 0, 87));
            jSeparator2.setBackground(new Color(63, 61, 86));
            jSeparator2.setForeground(new Color(63, 61, 86));
        } else {
            jSeparator1.setBackground(new Color(245, 0, 87));
            jSeparator1.setForeground(new Color(245, 0, 87));
            jSeparator2.setBackground(new Color(63, 61, 86));
            jSeparator2.setForeground(new Color(63, 61, 86));
             lbl_informcion.setText("");
        }


    }//GEN-LAST:event_txtpassMousePressed

    public void setColor(JPanel panel) {
        panel.setBackground(new Color(245, 0, 87));

    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new Color(63, 61, 86));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_Login;
    private javax.swing.JLabel lbl_fondo;
    private javax.swing.JLabel lbl_informcion;
    private javax.swing.JLabel lbl_of;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JPanel panel_principal;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
