/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_fondo;

import java.awt.Color;
import static javafx.scene.paint.Color.color;
import static javafx.scene.paint.Color.color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Ara-PC
 */
public class Blanco extends javax.swing.JFrame {

    /**
     * Creates new form Blanco
     */
    public Blanco() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        //txtUser.setText("");
        txtUser.setBackground(new Color(0, 0, 0, 0));
        txtPassword.setBackground(new Color(0, 0, 0, 0));
        lbl_button.setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lbl_exit = new javax.swing.JLabel();
        lbl_button = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_login = new javax.swing.JLabel();
        lbl_principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Please enter valid credentials.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, -1, -1));

        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cancel_35px.png"))); // NOI18N
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_exitMousePressed(evt);
            }
        });
        getContentPane().add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        lbl_button.setBackground(new java.awt.Color(255, 255, 255));
        lbl_button.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button (1).png"))); // NOI18N
        lbl_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_buttonMouseExited(evt);
            }
        });
        getContentPane().add(lbl_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 240, 70));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Administrator");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_secure_25px.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_male_user_25px.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 442, 330, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 330, 10));

        txtPassword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("Password");
        txtPassword.setBorder(null);
        txtPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPassword.setOpaque(false);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 290, 40));

        txtUser.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setText("Username");
        txtUser.setBorder(null);
        txtUser.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUser.setOpaque(false);
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 290, 40));

        lbl_password.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(255, 255, 255));
        lbl_password.setText("Password ");
        getContentPane().add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 90, -1));

        lbl_username.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("Username");
        getContentPane().add(lbl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 100, -1));

        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_group_150px.png"))); // NOI18N
        getContentPane().add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 150, 160));

        lbl_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_fondo/Sin título-1.png"))); // NOI18N
        getContentPane().add(lbl_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 390, 550));

        lbl_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.jpg"))); // NOI18N
        getContentPane().add(lbl_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        setSize(new java.awt.Dimension(900, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void lbl_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lbl_exitMousePressed

    private void lbl_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_buttonMouseEntered
        setColor(lbl_button);
    }//GEN-LAST:event_lbl_buttonMouseEntered

    private void lbl_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_buttonMouseExited
        // TODO add your handling code here
        resetColor(lbl_button);
    }//GEN-LAST:event_lbl_buttonMouseExited

    public void setColor(JLabel label) {
        label.setBackground(new Color(157, 54, 125));
    }

    public void resetColor(JLabel label) {

        label.setBackground(new Color(234, 90, 131));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Blanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Blanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Blanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Blanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Blanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_button;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_principal;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
