/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_calculadora;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static sun.net.www.http.HttpClient.New;

/**
 *
 * @author Ara-PC
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    private String cadena_Numero = "";
    private double numero = 0, resultado = 0;
    private String operacion = "nula";
    private boolean activado = true;
    private boolean clear = false;
    private int cont = 0;
    int x;
    int y;

    public Calculadora() {
        initComponents();

        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icons8_calculator_30px_2.png")).getImage()
        );
        setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null); // Ventana en el centro

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Header = new javax.swing.JPanel();
        lbl_exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_numero = new javax.swing.JLabel();
        lbl_pantalla = new javax.swing.JLabel();
        panel_division = new javax.swing.JPanel();
        lbl_division = new javax.swing.JLabel();
        panel_borrar = new javax.swing.JPanel();
        lbl_borrar = new javax.swing.JLabel();
        panel_cero = new javax.swing.JPanel();
        lbl_cero = new javax.swing.JLabel();
        panel_raiz = new javax.swing.JPanel();
        lbl_raiz = new javax.swing.JLabel();
        panel_9 = new javax.swing.JPanel();
        lbl_9 = new javax.swing.JLabel();
        panel_multi = new javax.swing.JPanel();
        lbl_multi = new javax.swing.JLabel();
        panel_7 = new javax.swing.JPanel();
        lbl_7 = new javax.swing.JLabel();
        panel_8 = new javax.swing.JPanel();
        lbl_8 = new javax.swing.JLabel();
        panel_4 = new javax.swing.JPanel();
        lbl_4 = new javax.swing.JLabel();
        panel_5 = new javax.swing.JPanel();
        lbl_5 = new javax.swing.JLabel();
        panel_6 = new javax.swing.JPanel();
        lbl_6 = new javax.swing.JLabel();
        panel_resta = new javax.swing.JPanel();
        lbl_resta = new javax.swing.JLabel();
        panel_suma = new javax.swing.JPanel();
        lbl_suma = new javax.swing.JLabel();
        panel_3 = new javax.swing.JPanel();
        lbl_3 = new javax.swing.JLabel();
        panel_2 = new javax.swing.JPanel();
        lbl_2 = new javax.swing.JLabel();
        panel_1 = new javax.swing.JPanel();
        lbl_1 = new javax.swing.JLabel();
        panel_masmenos = new javax.swing.JPanel();
        lbl_masmenos = new javax.swing.JLabel();
        panel_0 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panel_punto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_igual = new javax.swing.JPanel();
        lbl_igual = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        backgraund = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setIconImages(null);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Header.setBackground(new java.awt.Color(70, 130, 180));
        Panel_Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cancel_30px_1.png"))); // NOI18N
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_exitMousePressed(evt);
            }
        });
        Panel_Header.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 40, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_calculator_30px_2.png"))); // NOI18N
        jLabel2.setText("C A L C U L A T O R");
        Panel_Header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_macos_minimize_35px.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        Panel_Header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 40, 40));

        getContentPane().add(Panel_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 40));

        lbl_numero.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_numero.setForeground(new java.awt.Color(255, 255, 255));
        lbl_numero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_numero.setText("0");
        getContentPane().add(lbl_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 300, 90));

        lbl_pantalla.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_pantalla.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lbl_pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 50));

        panel_division.setBackground(new java.awt.Color(51, 51, 51));
        panel_division.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_divisionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_divisionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_divisionMousePressed(evt);
            }
        });
        panel_division.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_division.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_division.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_division_30px_1.png"))); // NOI18N
        panel_division.add(lbl_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(panel_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 50, 50));

        panel_borrar.setBackground(new java.awt.Color(51, 51, 51));
        panel_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_borrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_borrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_borrarMousePressed(evt);
            }
        });
        panel_borrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_borrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_clear_symbol_30px_1.png"))); // NOI18N
        panel_borrar.add(lbl_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 50, 50));

        panel_cero.setBackground(new java.awt.Color(51, 51, 51));
        panel_cero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_ceroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_ceroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_ceroMousePressed(evt);
            }
        });
        panel_cero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_cero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_copyright_30px.png"))); // NOI18N
        panel_cero.add(lbl_cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 50, 50));

        panel_raiz.setBackground(new java.awt.Color(51, 51, 51));
        panel_raiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_raizMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_raizMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_raizMousePressed(evt);
            }
        });
        panel_raiz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_raiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_raiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_root_30px.png"))); // NOI18N
        panel_raiz.add(lbl_raiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_raiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 50, 50));

        panel_9.setBackground(new java.awt.Color(51, 51, 51));
        panel_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_9MousePressed(evt);
            }
        });
        panel_9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_9_key_30px.png"))); // NOI18N
        panel_9.add(lbl_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 50, 50));

        panel_multi.setBackground(new java.awt.Color(51, 51, 51));
        panel_multi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_multiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_multiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_multiMousePressed(evt);
            }
        });
        panel_multi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_multi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_multi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_multiplication_30px.png"))); // NOI18N
        panel_multi.add(lbl_multi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_multi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 50, 50));

        panel_7.setBackground(new java.awt.Color(51, 51, 51));
        panel_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_7MousePressed(evt);
            }
        });
        panel_7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_7_30px.png"))); // NOI18N
        panel_7.add(lbl_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 50, 50));

        panel_8.setBackground(new java.awt.Color(51, 51, 51));
        panel_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_8MousePressed(evt);
            }
        });
        panel_8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_8_key_30px_1.png"))); // NOI18N
        panel_8.add(lbl_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 50, 50));

        panel_4.setBackground(new java.awt.Color(51, 51, 51));
        panel_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_4MousePressed(evt);
            }
        });
        panel_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_4_30px.png"))); // NOI18N
        panel_4.add(lbl_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 50, 50));

        panel_5.setBackground(new java.awt.Color(51, 51, 51));
        panel_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_5MousePressed(evt);
            }
        });
        panel_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_5_30px.png"))); // NOI18N
        panel_5.add(lbl_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 50, 50));

        panel_6.setBackground(new java.awt.Color(51, 51, 51));
        panel_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_6MousePressed(evt);
            }
        });
        panel_6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_6_30px.png"))); // NOI18N
        panel_6.add(lbl_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 50, 50));

        panel_resta.setBackground(new java.awt.Color(51, 51, 51));
        panel_resta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_restaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_restaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_restaMousePressed(evt);
            }
        });
        panel_resta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_resta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_resta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_reduce_30px.png"))); // NOI18N
        panel_resta.add(lbl_resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 50, 50));

        panel_suma.setBackground(new java.awt.Color(51, 51, 51));
        panel_suma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_sumaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_sumaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_sumaMousePressed(evt);
            }
        });
        panel_suma.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_suma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_suma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_sum_30px.png"))); // NOI18N
        panel_suma.add(lbl_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 50, 50));

        panel_3.setBackground(new java.awt.Color(51, 51, 51));
        panel_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_3MousePressed(evt);
            }
        });
        panel_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_3_30px_1.png"))); // NOI18N
        panel_3.add(lbl_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 50, 50));

        panel_2.setBackground(new java.awt.Color(51, 51, 51));
        panel_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_2MousePressed(evt);
            }
        });
        panel_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_2_30px.png"))); // NOI18N
        panel_2.add(lbl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 50, 50));

        panel_1.setBackground(new java.awt.Color(51, 51, 51));
        panel_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_1MousePressed(evt);
            }
        });
        panel_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_1_30px.png"))); // NOI18N
        panel_1.add(lbl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 50, 50));

        panel_masmenos.setBackground(new java.awt.Color(51, 51, 51));
        panel_masmenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_masmenosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_masmenosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_masmenosMousePressed(evt);
            }
        });
        panel_masmenos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_masmenos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_masmenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_plus_and_minus_30px.png"))); // NOI18N
        panel_masmenos.add(lbl_masmenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 10, 40, 30));

        getContentPane().add(panel_masmenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 50, 50));

        panel_0.setBackground(new java.awt.Color(51, 51, 51));
        panel_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_0MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_0MousePressed(evt);
            }
        });
        panel_0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_0_key_30px_1.png"))); // NOI18N
        panel_0.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 50, 50));

        panel_punto.setBackground(new java.awt.Color(51, 51, 51));
        panel_punto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_puntoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_puntoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_puntoMousePressed(evt);
            }
        });
        panel_punto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_sphere_30px_1.png"))); // NOI18N
        panel_punto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        getContentPane().add(panel_punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 50, 50));

        panel_igual.setBackground(new java.awt.Color(51, 51, 51));
        panel_igual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_igualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_igualMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_igualMousePressed(evt);
            }
        });
        panel_igual.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_igual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_igual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_equals_30px.png"))); // NOI18N
        panel_igual.add(lbl_igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        getContentPane().add(panel_igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 50, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 300, -1));

        backgraund.setBackground(new java.awt.Color(0, 255, 127));
        backgraund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Transparente.png"))); // NOI18N
        backgraund.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgraundMouseDragged(evt);
            }
        });
        backgraund.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgraundMousePressed(evt);
            }
        });
        getContentPane().add(backgraund, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 550));

        setSize(new java.awt.Dimension(300, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     int clicks = 0;
    boolean val;
    private void lbl_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMousePressed

        Ventana v = new Ventana();
        v.setVisible(true);
        

    }//GEN-LAST:event_lbl_exitMousePressed

    private void backgraundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgraundMouseDragged
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        this.setLocation(x1 - x, y1 - y);
    }//GEN-LAST:event_backgraundMouseDragged

    private void backgraundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgraundMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_backgraundMousePressed

    private void panel_ceroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ceroMouseEntered
        setColor(panel_cero);
    }//GEN-LAST:event_panel_ceroMouseEntered

    private void panel_ceroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ceroMouseExited
        resetColor(panel_cero);
    }//GEN-LAST:event_panel_ceroMouseExited

    private void panel_raizMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_raizMouseEntered
        // TODO add your handling code here:
        setColor(panel_raiz);
    }//GEN-LAST:event_panel_raizMouseEntered

    private void panel_raizMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_raizMouseExited
        // TODO add your handling code here:
        resetColor(panel_raiz);
    }//GEN-LAST:event_panel_raizMouseExited

    private void panel_divisionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_divisionMouseEntered
        // TODO add your handling code here:
        setColor(panel_division);
    }//GEN-LAST:event_panel_divisionMouseEntered

    private void panel_divisionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_divisionMouseExited
        // TODO add your handling code here:
        resetColor(panel_division);
    }//GEN-LAST:event_panel_divisionMouseExited

    private void panel_borrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_borrarMouseEntered
        // TODO add your handling code here:
        setColor(panel_borrar);
    }//GEN-LAST:event_panel_borrarMouseEntered

    private void panel_borrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_borrarMouseExited
        // TODO add your handling code here:
        resetColor(panel_borrar);
    }//GEN-LAST:event_panel_borrarMouseExited

    private void panel_7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_7MouseEntered
        // TODO add your handling code here:
        setColor(panel_7);
    }//GEN-LAST:event_panel_7MouseEntered

    private void panel_7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_7MouseExited
        // TODO add your handling code here:
        resetColor(panel_7);
    }//GEN-LAST:event_panel_7MouseExited

    private void panel_8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_8MouseEntered
        // TODO add your handling code here:
        setColor(panel_8);
    }//GEN-LAST:event_panel_8MouseEntered

    private void panel_8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_8MouseExited
        // TODO add your handling code here:
        resetColor(panel_8);
    }//GEN-LAST:event_panel_8MouseExited

    private void panel_9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_9MouseEntered
        // TODO add your handling code here:
        setColor(panel_9);
    }//GEN-LAST:event_panel_9MouseEntered

    private void panel_9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_9MouseExited
        // TODO add your handling code here:
        resetColor(panel_9);
    }//GEN-LAST:event_panel_9MouseExited

    private void panel_multiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_multiMouseEntered
        // TODO add your handling code here:
        setColor(panel_multi);
    }//GEN-LAST:event_panel_multiMouseEntered

    private void panel_multiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_multiMouseExited
        // TODO add your handling code here:
        resetColor(panel_multi);
    }//GEN-LAST:event_panel_multiMouseExited

    private void panel_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_4MouseEntered
        // TODO add your handling code here:
        setColor(panel_4);
    }//GEN-LAST:event_panel_4MouseEntered

    private void panel_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_4MouseExited
        resetColor(panel_4);
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_4MouseExited

    private void panel_5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_5MouseEntered
        // TODO add your handling code here:
        setColor(panel_5);
    }//GEN-LAST:event_panel_5MouseEntered

    private void panel_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_5MouseExited
        // TODO add your handling code here:
        resetColor(panel_5);
    }//GEN-LAST:event_panel_5MouseExited

    private void panel_6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_6MouseEntered
        // TODO add your handling code here:
        setColor(panel_6);
    }//GEN-LAST:event_panel_6MouseEntered

    private void panel_6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_6MouseExited
        // TODO add your handling code here:
        resetColor(panel_6);
    }//GEN-LAST:event_panel_6MouseExited

    private void panel_restaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_restaMouseEntered
        // TODO add your handling code here:
        setColor(panel_resta);
    }//GEN-LAST:event_panel_restaMouseEntered

    private void panel_restaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_restaMouseExited
        // TODO add your handling code here:
        resetColor(panel_resta);
    }//GEN-LAST:event_panel_restaMouseExited

    private void panel_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_1MouseEntered
        // TODO add your handling code here:
        setColor(panel_1);
    }//GEN-LAST:event_panel_1MouseEntered

    private void panel_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_1MouseExited
        // TODO add your handling code here:
        resetColor(panel_1);
    }//GEN-LAST:event_panel_1MouseExited

    private void panel_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_2MouseEntered
        // TODO add your handling code here:
        setColor(panel_2);
    }//GEN-LAST:event_panel_2MouseEntered

    private void panel_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_2MouseExited
        // TODO add your handling code here:
        resetColor(panel_2);
    }//GEN-LAST:event_panel_2MouseExited

    private void panel_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_3MouseEntered
        // TODO add your handling code here:
        setColor(panel_3);
    }//GEN-LAST:event_panel_3MouseEntered

    private void panel_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_3MouseExited
        // TODO add your handling code here:
        resetColor(panel_3);
    }//GEN-LAST:event_panel_3MouseExited

    private void panel_sumaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_sumaMouseEntered
        // TODO add your handling code here:
        setColor(panel_suma);
    }//GEN-LAST:event_panel_sumaMouseEntered

    private void panel_sumaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_sumaMouseExited
        // TODO add your handling code here:
        resetColor(panel_suma);
    }//GEN-LAST:event_panel_sumaMouseExited

    private void panel_masmenosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_masmenosMouseEntered
        // TODO add your handling code here:
        setColor(panel_masmenos);
    }//GEN-LAST:event_panel_masmenosMouseEntered

    private void panel_masmenosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_masmenosMouseExited
        // TODO add your handling code here:
        resetColor(panel_masmenos);
    }//GEN-LAST:event_panel_masmenosMouseExited

    private void panel_0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_0MouseEntered
        // TODO add your handling code here:
        setColor(panel_0);
    }//GEN-LAST:event_panel_0MouseEntered

    private void panel_0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_0MouseExited
        // TODO add your handling code here:
        resetColor(panel_0);
    }//GEN-LAST:event_panel_0MouseExited

    private void panel_puntoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_puntoMouseEntered
        // TODO add your handling code here:
        setColor(panel_punto);
    }//GEN-LAST:event_panel_puntoMouseEntered

    private void panel_puntoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_puntoMouseExited
        // TODO add your handling code here:
        resetColor(panel_punto);
    }//GEN-LAST:event_panel_puntoMouseExited

    private void panel_igualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_igualMouseEntered
        // TODO add your handling code here:
        setColor(panel_igual);
    }//GEN-LAST:event_panel_igualMouseEntered

    private void panel_igualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_igualMouseExited
        // TODO add your handling code here:
        resetColor(panel_igual);
    }//GEN-LAST:event_panel_igualMouseExited

    private void panel_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_1MousePressed
        // TODO add your handling code here:
        cadena_Numero += "1";
        lbl_numero.setText(cadena_Numero);
        activado = true;
    }//GEN-LAST:event_panel_1MousePressed

    private void panel_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_2MousePressed
        // TODO add your handling code here:
        cadena_Numero += "2";
        lbl_numero.setText(cadena_Numero);
        activado = true;

    }//GEN-LAST:event_panel_2MousePressed

    private void panel_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_3MousePressed
        // TODO add your handling code here:
        cadena_Numero += "3";
        lbl_numero.setText(cadena_Numero);
        activado = true;
    }//GEN-LAST:event_panel_3MousePressed

    private void panel_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_4MousePressed
        // TODO add your handling code here:
        cadena_Numero += "4";
        lbl_numero.setText(cadena_Numero);
        activado = true;
    }//GEN-LAST:event_panel_4MousePressed

    private void panel_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_5MousePressed
        cadena_Numero += "5";
        lbl_numero.setText(cadena_Numero);
        activado = true;
    }//GEN-LAST:event_panel_5MousePressed

    private void panel_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_6MousePressed
        // TODO add your handling code here:
        cadena_Numero += "6";
        lbl_numero.setText(cadena_Numero);
        activado = true;
    }//GEN-LAST:event_panel_6MousePressed

    private void panel_7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_7MousePressed
        cadena_Numero += "7";
        lbl_numero.setText(cadena_Numero);
        activado = true;
    }//GEN-LAST:event_panel_7MousePressed

    private void panel_8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_8MousePressed
        // TODO add your handling code here:
        cadena_Numero += "8";
        lbl_numero.setText(cadena_Numero);
        activado = true;
    }//GEN-LAST:event_panel_8MousePressed

    private void panel_9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_9MousePressed
        // TODO add your handling code here:
        cadena_Numero += "9";
        lbl_numero.setText(cadena_Numero);
        activado = true;
    }//GEN-LAST:event_panel_9MousePressed

    private void panel_0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_0MousePressed
        // TODO add your handling code here:
        if (!cadena_Numero.equals("")) {
            cadena_Numero += "0";
            lbl_numero.setText(cadena_Numero);
            activado = true;
        }
    }//GEN-LAST:event_panel_0MousePressed

    private void panel_sumaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_sumaMousePressed
        // TODO add your handling code here:
        int tamano = cadena_Numero.length();
        if (tamano > 0) {
            if (activado == true) {
                numero = Double.parseDouble(cadena_Numero);
                lbl_pantalla.setText(cadena_Numero + " + ");
                cadena_Numero = "";
                operacion = "Sumar";
                activado = false;
                clear = false;

            }
        }

    }//GEN-LAST:event_panel_sumaMousePressed

    private void panel_igualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_igualMousePressed
        // TODO add your handling code hereca
        double numero2;
        if (operacion.equalsIgnoreCase("Nula")) {
            lbl_pantalla.setText(cadena_Numero);
        } else if (operacion.equalsIgnoreCase("Sumar")) {
            numero2 = Double.parseDouble(cadena_Numero);
            resultado = numero + numero2;
            lbl_numero.setText(String.format("%.2f", resultado));
            cadena_Numero = String.valueOf(resultado);
            operacion = "Nula";
            //cadena_Numero = "";
        } else if (operacion.equalsIgnoreCase("Restar")) {
            numero2 = Double.parseDouble(cadena_Numero);
            resultado = numero - numero2;
            lbl_numero.setText(String.format("%.2f", resultado));
            cadena_Numero = String.valueOf(resultado);
            operacion = "Nula";
        } else if (operacion.equalsIgnoreCase("Multi")) {
            numero2 = Double.parseDouble(cadena_Numero);
            resultado = numero * numero2;
            lbl_numero.setText(String.format("%.2f", resultado));
            cadena_Numero = String.valueOf(resultado);
            operacion = "Nula";
        } else if (operacion.equalsIgnoreCase("Div")) {
            numero2 = Double.parseDouble(cadena_Numero);
            resultado = numero / numero2;
            lbl_numero.setText(String.format("%.2f", resultado));
            cadena_Numero = String.valueOf(resultado);
            operacion = "Nula";
        }
        lbl_pantalla.setText(" ");
        //cadena_Numero = "";
        activado = true;


    }//GEN-LAST:event_panel_igualMousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel4MousePressed

    private void panel_puntoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_puntoMousePressed
        // TODO add your handling code here:

        if (clear == false) {
            if (cadena_Numero.equals("")) {
                cadena_Numero = "0.";
            } else {

                cadena_Numero += ".";
            }
            lbl_numero.setText(cadena_Numero);
            clear = true;
        }

    }//GEN-LAST:event_panel_puntoMousePressed

    private void panel_masmenosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_masmenosMousePressed
        // TODO add your handling code here:
        int tamano = cadena_Numero.length();

        if (tamano > 0) {
            if (cadena_Numero.charAt(0) != '-') {

                cadena_Numero = "-" + cadena_Numero;

            } else {
                cadena_Numero = cadena_Numero.substring(1, cadena_Numero.length());
            }
            lbl_numero.setText(cadena_Numero);
        }
    }//GEN-LAST:event_panel_masmenosMousePressed

    private void panel_borrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_borrarMousePressed
        // TODO add your handling code here:
        int tamaño = cadena_Numero.length();
        if (tamaño > 0) {
            if (tamaño == 1) {
                cadena_Numero = "0";

            }
            cadena_Numero = cadena_Numero.substring(0, cadena_Numero.length() - 1);
            lbl_numero.setText(cadena_Numero);
        }
    }//GEN-LAST:event_panel_borrarMousePressed

    private void panel_restaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_restaMousePressed
        // TODO add your handling code here
        int tamano = cadena_Numero.length();
        if (tamano > 0) {
            if (activado == true) {
                numero = Double.parseDouble(cadena_Numero);
                lbl_pantalla.setText(cadena_Numero + " - ");
                cadena_Numero = "";
                operacion = "Restar";
                activado = false;
                clear = false;

            }

        }

    }//GEN-LAST:event_panel_restaMousePressed

    private void panel_multiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_multiMousePressed
        // TODO add your handling code here:
        int tamano = cadena_Numero.length();

        if (tamano > 0) {
            if (activado == true) {
                numero = Double.parseDouble(cadena_Numero);
                lbl_pantalla.setText(cadena_Numero + " x ");
                cadena_Numero = "";
                operacion = "Multi";
                activado = false;
                clear = false;

            }
        }
    }//GEN-LAST:event_panel_multiMousePressed

    private void panel_divisionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_divisionMousePressed
        // TODO add your handling code here:
        int tamano = cadena_Numero.length();

        if (tamano > 0) {
            if (activado == true) {
                numero = Double.parseDouble(cadena_Numero);
                lbl_pantalla.setText(cadena_Numero + " / ");
                cadena_Numero = "";
                operacion = "Div";
                activado = false;
                clear = false;

            }
        }
    }//GEN-LAST:event_panel_divisionMousePressed

    private void panel_raizMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_raizMousePressed
        // TODO add your handling code here:
        int tamano = cadena_Numero.length();

        if (tamano > 0) {
            if (activado == true) {
                numero = Double.parseDouble(cadena_Numero);
                lbl_pantalla.setText("sqrt(" + cadena_Numero + ")");
                cadena_Numero = "";
                resultado = Math.sqrt(numero);
                lbl_numero.setText(String.format("%.2f", resultado));
                cadena_Numero = String.valueOf(resultado);
                clear = false;

            }
        }
    }//GEN-LAST:event_panel_raizMousePressed

    private void panel_ceroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ceroMousePressed
        // TODO add your handling code here:
        lbl_numero.setText("0");
        lbl_pantalla.setText("");
        cadena_Numero = "";
        operacion = "nula";
        activado = true;
        clear = false;
    }//GEN-LAST:event_panel_ceroMousePressed

    public void setColor(JPanel panel) {
        panel.setBackground(new Color(70, 130, 180));

    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new Color(51, 51, 51));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Header;
    private javax.swing.JLabel backgraund;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_4;
    private javax.swing.JLabel lbl_5;
    private javax.swing.JLabel lbl_6;
    private javax.swing.JLabel lbl_7;
    private javax.swing.JLabel lbl_8;
    private javax.swing.JLabel lbl_9;
    private javax.swing.JLabel lbl_borrar;
    private javax.swing.JLabel lbl_cero;
    private javax.swing.JLabel lbl_division;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_igual;
    private javax.swing.JLabel lbl_masmenos;
    private javax.swing.JLabel lbl_multi;
    private javax.swing.JLabel lbl_numero;
    private javax.swing.JLabel lbl_pantalla;
    private javax.swing.JLabel lbl_raiz;
    private javax.swing.JLabel lbl_resta;
    private javax.swing.JLabel lbl_suma;
    private javax.swing.JPanel panel_0;
    private javax.swing.JPanel panel_1;
    private javax.swing.JPanel panel_2;
    private javax.swing.JPanel panel_3;
    private javax.swing.JPanel panel_4;
    private javax.swing.JPanel panel_5;
    private javax.swing.JPanel panel_6;
    private javax.swing.JPanel panel_7;
    private javax.swing.JPanel panel_8;
    private javax.swing.JPanel panel_9;
    private javax.swing.JPanel panel_borrar;
    private javax.swing.JPanel panel_cero;
    private javax.swing.JPanel panel_division;
    private javax.swing.JPanel panel_igual;
    private javax.swing.JPanel panel_masmenos;
    private javax.swing.JPanel panel_multi;
    private javax.swing.JPanel panel_punto;
    private javax.swing.JPanel panel_raiz;
    private javax.swing.JPanel panel_resta;
    private javax.swing.JPanel panel_suma;
    // End of variables declaration//GEN-END:variables
}
