/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_transparente;

import java.awt.Color;

/**
 *
 * @author Ara-PC
 */
public class Transparente extends javax.swing.JFrame {

    /**
     * Creates new form Transparente
     */
    int x;
    int y;

    public Transparente() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
       // txtsearch.setBackground(new Color(0, 0, 0, 0));

    
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Panel_Add = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Panel_Setting = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Panel_Home = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Panel_Airport = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Panel_Statics = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Panel_Contact = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        backgraund = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Imagenes/icons8_facebook_old_20px_1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 30, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Imagenes/icons8_whatsapp_20px.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, 30, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("New York");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Imagenes/icons8_play_button_20px.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 30, 30));

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(255, 255, 255));
        txtsearch.setText("Search");
        txtsearch.setBorder(null);
        txtsearch.setCaretColor(new java.awt.Color(255, 255, 255));
        txtsearch.setOpaque(false);
        txtsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtsearchMousePressed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 280, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 320, 10));

        Panel_Add.setBackground(new java.awt.Color(51, 51, 51));
        Panel_Add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Imagenes/icons8_plus_math_50px.png"))); // NOI18N
        Panel_Add.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, 60));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ADD");
        Panel_Add.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, -1));

        getContentPane().add(Panel_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 140, 140));

        Panel_Setting.setBackground(new java.awt.Color(51, 51, 51));
        Panel_Setting.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Imagenes/icons8_settings_50px_1.png"))); // NOI18N
        Panel_Setting.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, 60));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SETTING");
        Panel_Setting.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, -1));

        getContentPane().add(Panel_Setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 140, 140));

        Panel_Home.setBackground(new java.awt.Color(51, 51, 51));
        Panel_Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Imagenes/icons8_home_50px_4.png"))); // NOI18N
        Panel_Home.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, 60));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("HOME");
        Panel_Home.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, -1));

        getContentPane().add(Panel_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 140, 140));

        Panel_Airport.setBackground(new java.awt.Color(51, 51, 51));
        Panel_Airport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Imagenes/icons8_airport_50px.png"))); // NOI18N
        Panel_Airport.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 70, 60));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("AIRPORT");
        Panel_Airport.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 70, -1));

        getContentPane().add(Panel_Airport, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 140, 140));

        Panel_Statics.setBackground(new java.awt.Color(51, 51, 51));
        Panel_Statics.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Imagenes/icons8_combo_chart_50px.png"))); // NOI18N
        Panel_Statics.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, 60));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("STATISTICS");
        Panel_Statics.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, -1));

        getContentPane().add(Panel_Statics, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 140, 140));

        Panel_Contact.setBackground(new java.awt.Color(51, 51, 51));
        Panel_Contact.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Imagenes/icons8_contacts_50px.png"))); // NOI18N
        Panel_Contact.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, 60));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("CONTACT");
        Panel_Contact.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, -1));

        getContentPane().add(Panel_Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 140, 140));

        jPanel1.setBackground(new java.awt.Color(163, 247, 191));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Imagenes/icons8_search_30px_3.png"))); // NOI18N
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 137, 40, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("AIRLINE");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 230, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Imagenes/icons8_airplane_take_off_100px_1.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 110));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Imagenes/icons8_close_window_30px_1.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel19MousePressed(evt);
            }
        });
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 130));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Imagenes/icons8_search_30px_2.png"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 40, 30));

        backgraund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_transparente/Transparente.png"))); // NOI18N
        backgraund.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgraundMouseDragged(evt);
            }
        });
        backgraund.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgraundMousePressed(evt);
            }
        });
        getContentPane().add(backgraund, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 890, 600));

        setSize(new java.awt.Dimension(888, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backgraundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgraundMouseDragged
        // TODO add your handling code here:
        int x1 = evt.getXOnScreen();
        int y1 = evt.getYOnScreen();
        this.setLocation(x1 - x, y1 - y);
    }//GEN-LAST:event_backgraundMouseDragged

    private void backgraundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgraundMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_backgraundMousePressed

    private void jLabel19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel19MousePressed

    private void txtsearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMousePressed
        // TODO add your handling code here:
        txtsearch.setText(" ");
        if (txtsearch.getText().length() > 1) {
            txtsearch.setText("");
        }
    }//GEN-LAST:event_txtsearchMousePressed

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtsearchKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transparente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transparente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transparente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transparente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transparente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Add;
    private javax.swing.JPanel Panel_Airport;
    private javax.swing.JPanel Panel_Contact;
    private javax.swing.JPanel Panel_Home;
    private javax.swing.JPanel Panel_Setting;
    private javax.swing.JPanel Panel_Statics;
    private javax.swing.JLabel backgraund;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
